title: a github pages corse
author: Rayfb-13
email: no-email!
description: > # this means to ignore newlines until "baseurl:"
  R
  
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
